FROM openjdk:11.0

ADD target/demo-0.0.1-SNAPSHOT.jar app.jar

RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/MYSCHEMA?allowPublicKeyRetrieval=true&useSSL=falseserverTimezone=UTC > application.properties'
RUN sh -c 'echo spring.datasource.username=root    >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre >> application.properties'

RUN sh -c 'echo spring.redis.host=redis > application.properties'
RUN sh -c 'echo spring.redis.port=6379    >> application.properties'

VOLUME /tmp


CMD ["--server.port=8081"]

EXPOSE 8081

ENTRYPOINT ["java","-jar","/app.jar"]
